# Generated by Django 2.2.7 on 2019-12-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='location',
            name='estate',
            field=models.CharField(default=True, max_length=60),
        ),
    ]
